const TYPES = {
  SET_JWT: "SET_JWT_SUCCESSES",
  SET_JWT_ERROR: "SET_JWT_ERROR",
  SET_JWT_SAGA: "SET_JWT_REQUEST",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_CURRENT_PAGE_SAGA: "SET_CURRENT_PAGE_REQUEST",
  SET_MENU_STATE:"SET_MENU_STATE",
  SET_MENU_STATE_SAGA:"SET_MENU_STATE_REQUEST",
  SET_IS_LOGIN:"SET_IS_LOGIN",
  SET_IS_LOGIN_SAGA:"SET_IS_LOGIN_REQUEST",
  SET_TYPE_OF_STORAGE: "SET_TYPE_OF_STORAGE",
  SET_TYPE_OF_STORAGE_SAGA:"SET_TYPE_OF_STORAGE_REQUEST",
  AUTHORSTYPES : {
    SET_MODE_VIEW: "SET_MODE_VIEW",
    SET_MODE_VIEW_SAGA: "SET_MODE_VIEW_REQUEST",
    SET_COUNT_VIEW: "SET_COUNT_VIEW",
    SET_COUNT_VIEW_SAGA: "SET_COUNT_VIEW_REQUEST",
    SET_CURRENT_PAGE_USERS_POSTS: "SET_CURRENT_PAGE_USERS_POSTS",
    SET_CURRENT_PAGE_USERS_POSTS_SAGA: "SET_CURRENT_PAGE_USERS_POSTS_REQUEST"
  }
}

export default TYPES

